export const APP = {
	MODAL_SHOW: 'MODAL_SHOW',
	MODAL_HIDE: 'MODAL_HIDE',
	GALLERY_SHOW: 'GALLERY_SHOW',
	GALLERY_HIDE: 'GALLERY_HIDE',
	SUCCESS_SHOW: 'SUCCESS_SHOW',
	SUCCESS_HIDE: 'SUCCESS_HIDE',
}